#ifndef RESOURCE_ID_H_
#define RESOURCE_ID_H_

#include "wx/defs.h"

enum {
  ID_READ_DB_THREAD = wxID_HIGHEST + 1,
  ID_LOGIN_TEXT_BUTTON,
  ID_REGISTER_TEXT_BUTTON,
  ID_REGISTER_PANEL_OK_BUTTON,
  ID_REGISTER_PANEL_CANCEL_BUTTON,
  ID_REGISTER_PANEL_BITMAP_BUTTON,

  ID_TEXT_PANEL_ACCOUNT,
  ID_TEXT_PANEL_PASSWORD,
  ID_TEXT_PANEL_CONFIRM_PASSWORD,
  ID_TEXT_PANEL_NAME,
  ID_TEXT_PANEL_GENDER,
  ID_TEXT_PANEL_AGE,
  ID_TEXT_PANEL_BIRTHDAY,
  ID_TEXT_CTRL_EMAIL,
  ID_TEXT_CTRL_COMMENTS,

  ID_REGISTER_PANEL_RADIO_BUTTON_MALE,
  ID_REGISTRE_PANEL_RADIO_BUTTON_FEMALE,

  ID_REGISTER_PANEL_COMBOBOX,

};

#endif  // RESOURCE_ID_H_
